pku-lemonade/review

- docs/data/software/ds.csv
- Add new papers on cache eviction and parallel strategies
- Update entries related to memory management and general applications
**Tags:**
> Add new papers about sp, classic papers, OSDI-25

- docs/data/hardware/fail.csv
> Add papers about failslow and NoC fault.

- docs/data/software/algorithm.csv
- docs/data/software/ds.csv
- docs/data/software/hpc.csv
- docs/data/software/os.csv
- docs/data/software/perf.csv
- docs/data/software/pl.csv
> refactor: modify software category

- docs/data/software/algorithm.csv
- docs/data/software/ds.csv
- docs/data/software/hpc.csv
- docs/data/software/os.csv
- docs/data/software/perf.csv
- docs/data/software/pl.csv
> refactor: modify the description in software to make them more meaningful

- docs/data/hardware/memory.csv
- docs/data/software/ds.csv
> Add papers from PIMnet's reference list to analyze their writing structure

- docs/data/hardware/memory.csv
> Week 17 & Week 20 papers

- docs/data/software/perf.csv
> Add papers about network tomography and graph analysis.

- docs/data/software/pl.csv
> Add papers about an author search about STEPHEN CHOU

- docs/data/software/pl.csv
**Tags:**
**I have limited exploration on HLS, so i have almost no idea about what idea in a paper is novel or isn't. Novelty will be updated in future when i have explored enough papers to get good information about this field.**
> Add a broad search on HLS within FPGA 22-25

- docs/data/hardware/accelerators.csv
- docs/data/software/algorithm.csv
> Papers about quantization.

- docs/data/software/algorithm.csv
- docs/data/software/ds.csv
- docs/data/software/pl.csv
The papers on are the following topics:
- ring-attention: split computation and communication to different device
- scaling law: the original paper and recent parallel scaling
- dl compiler: inspired by a talk by Prof Jidong Zhai
**Tags:**
> Add papers on ring-attention, scaling-law and dl-compiler

- docs/data/software/perf.csv
> Add papers about burst detection through author-focused search and about RCA.

- docs/data/hardware/memory.csv
> Add papers about PIM compilers and offload strategies from PIM-malloc's reference list.

- docs/data/software/algorithm.csv
- docs/data/software/perf.csv
> Add papers about distribution parameter estimation through broad search.

- docs/data/hardware/memory.csv
- docs/data/software/os.csv
> Add author-focused papers from Onur Mutlu

- docs/data/software/perf.csv
> Add papers about more types of burst detection through citation chasing of BurstSketch.

- docs/data/hardware/accelerators.csv
- docs/data/software/ds.csv
> Add 2 papers about a cite-chasing on Graphicionado.

- docs/data/hardware/accelerators.csv
- docs/data/software/ds.csv
This week's paper contains the following two types:
1. arXiv search: I check arXiv daily. But recently, the cool papers in DS type is fewer. The inference systems are paying more attention on RL infra (finding new topics).
2. classic papers: to help me build a comprehensive overview.
**Tags:**
> Add papers on arXiv search and classic papers

- docs/data/software/algorithm.csv
**Tags:**
Just realized that I forgot to create Pull Request lask week.
> post training quantization related papers

- docs/data/software/ds.csv
- docs/data/software/pl.csv
This week's paper covers the following aspects:
- Megatron: include Megatron2 and Megatron3. Learns a lot about all kinds of parallel
- arXiv search: find an paper closely connected with my work. And some other papers.
- TileLang: a DL compile framework, quiet impressive.
To be honest, most papers on arXiv talking about LLM system are quiet boring. We are waiting for some really new simple and effective ideas.
**Tags:**
> Add papers on Megatron and arXiv search

- docs/data/software/ds.csv
- docs/data/software/pl.csv
> Had a broad search about distributed algorithms on PPoPP 24'.

- docs/data/software/perf.csv
> Add papers about extended Berkeley Packet Filter through broad search.

- docs/data/hardware/memory.csv
- docs/data/hardware/network.csv
- docs/data/software/os.csv
Mainly from Prof. Guangyu Sun's group meeting this Sunday.
**Tags:**
> Add papers mentioned from ISCA 2025's quick overview

- docs/data/hardware/accelerators.csv
- docs/data/hardware/memory.csv
> Add few papers about a cite chasing on graphicionado (Piccolo is not added since is in)

- docs/data/software/algorithm.csv
- docs/data/software/ds.csv
> Add a broad search upon classic LLM quant methods & latest memory manage methods

- docs/data/hardware/memory.csv
- docs/data/hardware/parallel.csv
- docs/data/software/ds.csv
> Add papers related to novel memory architecture from ATC '25

- docs/data/hardware/accelerators.csv
- docs/data/hardware/network.csv
- docs/data/software/perf.csv
> Add papers about reconfigurable DNN accelerators through citation chasing of FRED.

- docs/data/hardware/accelerators.csv
> Added 2 creafully read papers on graph accelerators

- docs/data/hardware/memory.csv
- docs/data/software/algorithm.csv
**Tags:**
This weeks paper contains one highly related architecture-algorithm codesign paper about SRAM PIM for DNN accelerator. And also two papers about DNN training.
> Zyb 2025 week30

- docs/data/hardware/memory.csv
- docs/data/hardware/parallel.csv
Reading these papers might help me to decide what topic to do next.
**Tags:**
> Add author-focused search papers of Zhe Zhou & Cong Li, PKU.

- docs/data/software/algorithm.csv
- docs/data/software/perf.csv
> Add papers about DNN training, GPU performance prediction and data tracing from ASPLOS'25.

- docs/data/hardware/accelerators.csv
- docs/data/hardware/parallel.csv
- docs/data/hardware/processor.csv
- docs/data/software/pl.csv
> Add 3 papers on MLIR in w33 & add 3 papers from ISCA'25 in w35 (another from ISCA'25 duplicated)

- docs/data/hardware/accelerators.csv
- docs/data/hardware/parallel.csv
- docs/data/software/ds.csv
- docs/data/software/os.csv
- docs/data/software/perf.csv
> Add papers about SW26010 and some of the papers in Menghao Zhang's PPT.

- docs/data/hardware/memory.csv
- docs/data/software/algorithm.csv
**Tags:**
This week's paper includes some SRAM CIM hardware-software co-design papers, and some QAT papers.
> QAT & SRAM CIM related papers

- docs/data/software/ds.csv
- docs/data/software/os.csv
- docs/data/software/perf.csv
> Add 4 papers from a careful paper-reading of SOSP '25.

- docs/data/software/perf.csv
> Add papers about distributed tracing through citation chasing of Mint.

- docs/data/software/algorithm.csv
- docs/data/software/ds.csv
- docs/data/software/perf.csv
> Add papers about online root cause analysis, especially in microservice system through broad search.

- docs/data/hardware/eda.csv
- docs/data/software/pl.csv
> Added 4 papers from a cite chasing of HECTOR

- docs/data/hardware/perf.csv
- docs/data/software/ds.csv
- docs/data/software/perf.csv
> Add papers about thermal modeling, simulation and optimization.

- docs/data/hardware/memory.csv
- docs/data/hardware/network.csv
- docs/data/hardware/parallel.csv
- docs/data/software/algorithm.csv
- docs/data/software/ds.csv
These papers are mainly from the dLLM survey paper.
**Tags:**
> Add papers related to DLM and inference optimizations.

- docs/data/hardware/accelerators.csv
- docs/data/hardware/memory.csv
- docs/data/software/algorithm.csv
> Analog CIM papers, including DSE and training.

- docs/data/hardware/accelerators.csv
- docs/data/hardware/eda.csv
- docs/data/software/pl.csv
> Add 3 papers from PLDI'22 Hardware section

- docs/data/software/algorithm.csv
- docs/data/software/ds.csv
- docs/data/software/os.csv
> Add papers on dLLM and arxiv search

- docs/data/hardware/perf.csv
- docs/data/hardware/processor.csv
- docs/data/software/perf.csv
- docs/data/software/pl.csv
> Added 4 papers from MICRO '24

- docs/data/hardware/perf.csv
- docs/data/software/perf.csv
> Add papers about dataflow architecture and operator fusion co-design.
